METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 207
    adj_path: "../data/METRLA/adj_mx.pkl"
    L: 2
    K: 16
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 325
    adj_path: "../data/PEMSBAY/adj_mx_bay.pkl"
    L: 2
    K: 16
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 358
    adj_path: "../data/PEMS03/adj_PEMS03.pkl"
    L: 2
    K: 16
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 307
    adj_path: "../data/PEMS04/adj_PEMS04.pkl"
    L: 2
    K: 16
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 32
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 883
    adj_path: "../data/PEMS07/adj_PEMS07.pkl"
    L: 2
    K: 12
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 170
    adj_path: "../data/PEMS08/adj_PEMS08.pkl"
    L: 2
    K: 16
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMSD7M:
  num_nodes: 228
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 228
    adj_path: "../data/PEMSD7M/adj_PEMSD7M_distance.pkl"
    L: 2
    K: 16
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1

PEMSD7L:
  num_nodes: 1026
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  y_time_of_day: True
  y_day_of_week: True

  runner: STDN
  pass_device: True

  lr: 0.001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 32
  max_epochs: 200
  early_stop: 20

  model_args:
    num_of_vertices: 1026
    adj_path: "../data/PEMSD7L/adj_PEMSD7L_distance.pkl"
    L: 2
    K: 12
    d: 8
    node_miss_rate: 0.1
    T_miss_len: 12
    order: 3
    reference: 3
    time_slice_size: 5
    num_his: 12
    num_pred: 12
    in_channels: 1
    out_channels: 1
    bn_decay: 0.1
